### ISSUE TITLE
Check Alexnet to improve the accuracy obtained

### ISSUE THREAD

**Issue by PrajwalaTM** [PrajwalaTM/tomato-leaf-disease-detection#1]
Note: LRN layers have been replaced with BatchNormalisation for the sake of simplicity.
Generate train_images_alexnet.npy and  train_labels_alexnet.npy by changing the size to (227,227) in the training_data.py and running the same.

**Comment by sangeetha-137** [comment]
how to convert image  dataset into .npy file

**Comment by PrajwalaTM** [comment]
Closing.
