### ISSUE TITLE
How to get the dataset

### ISSUE THREAD

**Issue by BestSongEver** [PrajwalaTM/tomato-leaf-disease-detection#2]
Hi
I aappreciate ur work a lot. But i am new here and i don't know how to get ur dataset from ur code.
Can u please show me how to get dataset.tar.gz with images of 10 classes of tomato leaves?
Thx a lot.

the best wishes

**Comment by PrajwalaTM** [comment]
Are you unable to extract dataset after cloning?

**Comment by BestSongEver** [comment]
I am afraid so.
The code was just 8.13kb when i choes "Download Zip" and it was within 60kb when i cloned it with "git clone https://github.com/PrajwalaTM/tomato-leaf-disease-detection.git"
So i wonder how could i get the dataset.

Thx again
@PrajwalaTM

**Comment by PrajwalaTM** [comment]
Oh alright. I've uploaded the dataset on the drive. 
You can access it from here:
https://drive.google.com/open?id=1DVy0LyUUfJciyo7BUFm1sHKSRdTVJgjF

**Comment by IqraMehmeen** [comment]
hi..
Can u please share the steps for execution of plant leaf disease detection

**Comment by PrajwalaTM** [comment]
Use the training_data.py script to generate train images and train labels and then run the ipython notebook
