### ISSUE TITLE
showing index error : tuple index out of range 

### ISSUE THREAD

**Issue by TahminaTashrif** [PrajwalaTM/tomato-leaf-disease-detection#3]
# Test pretrained model
train_images = np.array(train_images)
train_labels = np.array(train_labels)
mean = np.mean(train_images,axis=(0,1,2,3))
std = np.std(train_images,axis=(0,1,2,3))
train_images = (train_images-mean)/(std+1e-7)
num_classes = 10
train_labels = np_utils.to_categorical(train_labels,num_classes)

**Comment by PrajwalaTM** [comment]
Can you check if the arrays - train_images and train_labels are populated correctly and not empty?
